spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: mirzayev2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 4e5e6d4cf3bb95
    password: 3d2976e5623efe
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000




jwt:
  token:
    secret: f9b62abb0dcc765f03c0efff7a8e0ee4b31017fce3672c3eb56c296803bf643c50b1cb55080ef405b140f92710702fc932284eeac227e46689ef72994c68cc0c
    token_validity: 86400000

server:
  servlet:
    context-path: /hotel-api
  port: 8081




springdoc:
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    display-request-duration: true
    operations-sorter: method
    path: /docs

